services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-shoppers-backend
    image: nest-shoppers-backend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: pingshop
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend-network
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pingshop
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - db-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - redis-data:/data

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
